### ISSUE TITLE
Your system in GDScript

### ISSUE THREAD

**Issue by aPletory** [grazianobolla/godot4-multiplayer-template#7]
Good morning,

I'm looking to develop a car racing game with server authority. The positions of the cars must therefore be validated by the physics of the server.
I'm testing with High Level but I'm having trouble with position shifts and teleports with the RPC functions.

Your system seems to correspond to what we want to do, is it possible to implement your system in GDScript?

Thank you in advance for your answer

**Comment by grazianobolla** [comment]
Hi, good morning!

Yes, it can be implemented in GDscript, but you will have to re write everything. Or maybe you can keep the C# code and do the rest in GDScript which is possible.

Independently from what you want to do, I do NOT think this framework suits a racing game. This is more oriented towards a FPS game. A racing game will face other challenges and advantages, and with my solution you won't be able to "leverage" the advantages.

Advantages like that you can very easily predict were a vehicle will be in the future based on current data (something that can not be done in a FPS game since movement is too erratic). Or challenges like vehicle to vehicle collision.

**Comment by aPletory** [comment]
Thank you for your quick reply.
We will try to replace the player with high speed cars to see the behavior. ^^

**Comment by grazianobolla** [comment]
Yes you can, and It will probably work just fine!
